export enum ErrorCode {
  FILE_ALREADY_EXISTS,
  FOLDER_ALREADY_EXISTS,
  FILE_NOT_EXISTS,
  FOLDER_NOT_EXISTS,
  PATH_NOT_EXISTS,
  INVALID_CMD,
  NOT_BELONG_TO,
  DESTINATION_NOT_IDENTIFY,
  CURRENT_PATH_NOT_EXISTS
}